### PR TITLE
Add utility functions to auto-generated classes.

### LINKED ISSUE #77: Why is `ApiAccount.wallet` a String instead of a Dictionary?
Relevant line: https://github.com/heroiclabs/nakama-godot/blob/522f01fd4dea8b72ed66bfbe994cb623159c4595/addons/com.heroiclabs.nakama/api/NakamaAPI.gd#L213

This is pretty confusing, especially since an empty wallet string that looks like a Dictionary ("{}") is returned alongside the actual user Dictionary in the same `ApiAccount` object.

### PR DESCRIPTION
**Pull request by Faless**
Defined in a map in the generation script.
For now includes an extra property "wallet_dict" that parses (and caches) the wallet string from json.

Fixes #77

### CODE REVIEW

**Comment by novabyte** [comment]
Nice one @Faless I think this is a good solution to handle the special cases where we want to make it easier to decode the response type from JSON for developers. What do you think @lugehorsam ?

**Comment by lugehorsam** [comment]
I like it, assuming it's not possible for you to insert a non-dictionary via server-side code.

**Comment by novabyte** [comment]
@lugehorsam The user account wallet is always a JavaScript object returned by the API as an escaped JSON string (due to limitations with how to represent unstructured data in Protobuf).

**Comment by lugehorsam** [comment]
👍

**Pull request merged**
