### PR TITLE
Update Symbol Names to match Godot, Fix Request Call Args

### PR DESCRIPTION
**Pull request by beelol**
Change HTTPRequest -> HttpRequest to match Godot's new naming.

Change .Request call to contain 4 args to match new Godot signature for HttpRequest.Request

### CODE REVIEW

**Comment by ericburns** [comment]
@novabyte any update on pushing this change through? FWIW, I was stopping by to submit an identical PR. I'm working in Godot 4.2.1.stable.mono.official and this fixed it for me.

**Comment by lugehorsam** [comment]
Hey @ericburns and @beelol could either of you point us to where the naming has been changed? I still see it as `HTTPRequest` here -- https://docs.godotengine.org/en/stable/classes/class_httprequest.html 

If it is now `HttpRequest`, was it type-aliased to`HTTPRequest` for backwards compatibility? In other words, how would this code still be working?

**Comment by ericburns** [comment]
@lugehorsam looks like there is an open PR about fixing the documentation https://github.com/godotengine/godot/pull/84421

**Review by lugehorsam — APPROVED** [review]
thanks guys 🙏

**Pull request merged**
