### PR TITLE
[WIP] Godot4 (GDScript2) Support

### PR DESCRIPTION
**Pull request by elgansayer**
This is NOT ready. This is work in progress

This is simply a placeholder to force a conversation and gather contributors/conversations to help port this to gdscript2. 

Feel free to close if not allowed.

### CODE REVIEW

**Comment by elgansayer** [comment]
Can someone explain this codegen thing?

**Comment by elgansayer** [comment]
Most things are updated. 
Need a new design for the single yield. 
`var data = yield() # Manually resumed`

Then testing, 
Things to note are the bool to strings, new json class, and coroutine calls. With some luck it may just work

**Comment by dsnopek** [comment]
@elgansayer Thanks for starting on this! Can you sign the CLA per the comment above? I'm not sure your code can be considered for potential merge without having signed the CLA.

**Comment by elgansayer** [comment]
> @elgansayer Thanks for starting on this! Can you sign the CLA per the comment above? I'm not sure your code can be considered for potential merge without having signed the CLA.

I have done? I think the app hooks are not working? 
I have only to complete the yield thing but i've been too busy. It may require some proper restructuring of the code. sigh

**Comment by dsnopek** [comment]
> I have done? I think the app hooks are not working?

My understanding of the current error message, is that the email address on your commits (elgan.sayer@interfolio.com) doesn't match any of the email addresses on your GitHub account. So, perhaps you need to add that email to your GitHub under Settings -> Emails (you can have multiple emails beyond your primary)? If you already have it there, well, then I guess it is busted somehow. :-( You could try the "recheck" link in the comment up at the top?

> I have only to complete the yield thing but i've been too busy. It may require some proper restructuring of the code. sigh

Ok, thanks. I haven't had a chance to review what you've already done yet, but I hope to soon!

**Comment by elgansayer** [comment]
> > I have done? I think the app hooks are not working?
> 
> My understanding of the current error message, is that the email address on your commits ([elgan.sayer@interfolio.com](mailto:elgan.sayer@interfolio.com)) doesn't match any of the email addresses on your GitHub account. So, perhaps you need to add that email to your GitHub under Settings -> Emails (you can have multiple emails beyond your primary)? If you already have it there, well, then I guess it is busted somehow. :-( You could try the "recheck" link in the comment up at the top?
> 
> > I have only to complete the yield thing but i've been too busy. It may require some proper restructuring of the code. sigh
> 
> Ok, thanks. I haven't had a chance to review what you've already done yet, but I hope to soon!

Ahh! Silly me. I used my work PC didn't i. oops. :D Shh, They will never know :eyes: 

No worries. I really need to pick this back up again. I don't want it too far behind master/main branch!  This last yield doesnt seem too bad. It's just an event that needs reorganising. 

I would appreciate any feedback so we can get closer to a 4 branch.

**Comment by elgansayer** [comment]
It may be as simple as replaying it with await _conn. Need to study it more. Clears all the errors away.

I shall start attempting to build a demo project that can use the API.

**Comment by elgansayer** [comment]
Annoyingly gdscript2 seems unable to provide the property by name, it's likely a bug! but it's a bug thats hindering keeping the script structure the same. I'll investigate it a little more before bothering gd devs.

`cls.get("_SCHEMA")` always returns null :( 
The `const _SCHEMA`  also was not working so was changed to var. I am assuming bugs!

Any ideas anyone?

**Comment by dsnopek** [comment]
I've started poking around in your PR and attempting to get something minimally working. I've got my additions in PR #103

I suspect we may end up working on this in phases, where the 1st phase is getting something that works at all (with some workarounds for current the GDScript bugs), and then progressively making it better as we can remove the workarounds. But getting all the bugs reported early (and tracking them) will hopefully allow them to get fixed before the final Godot 4.0 releases, so we can have a nicely working client from day one.

**Comment by elgansayer** [comment]
ah fantastic! I see you noticed the same issues with getting property values but actually found the bug reports too! nice work and thanx for the time dedication!

It took me a while to find those bugs as i had to slowly crawl through unknown code. 

I see your workarounds too, Shame. I agree on the phrase strategy proposed.

Perhaps we should close this and focus on your draft? Mostly my changes since have been experiments with similar workarounds and trying to suss things out.

I basically look at this during my lunch hours. I will pause for now. Suggestions for todo are welcome.

**Comment by dsnopek** [comment]
Closing this one in favor of PR #103, which was just merged into the 'godot-4' branch

**Pull request closed without merging**
